# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "pg", "~> 1.5"

gem "rack", "~> 3.1"

gem "rack-session", "~> 2.0"

gem "rubocop", "~> 1.66"

gem "sinatra", "~> 4.0"

gem "rackup", "~> 2.1"

gem "httparty", "~> 0.22.0"
